---
apiVersion: v1
kind: Template
labels:
  template: "${APP_NAME}-${JOB_NAME}-backend-modules-bc-template"
metadata:
  name: "${APP_NAME}-${JOB_NAME}-backend-modules-bc"
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: "${APP_NAME}-${JOB_NAME}"
    name: "${APP_NAME}-${JOB_NAME}-backend-modules"
  spec:
    lookupPolicy:
      local: false
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: "${APP_NAME}-${JOB_NAME}"
    name: "${APP_NAME}-${JOB_NAME}-backend-modules"
  spec:
    completionDeadlineSeconds: 600
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: "${APP_NAME}-${JOB_NAME}-backend-modules:latest"
    postCommit: {}
    resources:
      requests:
        cpu: 1000m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 2Gi
    runPolicy: Serial
    source:
      images:
      - from:
          kind: ImageStreamTag
          name: "${APP_NAME}-${JOB_NAME}-backend-npm:latest"
          namespace: "${NAMESPACE}"
        paths:
        - destinationDir: npm-latest
          sourcePath: /opt/app-root/src
      dockerfile: |-
        FROM mhart/alpine-node:10
        WORKDIR /opt/app-root/src
        COPY npm-latest/src/node_modules ./node_modules
    strategy:
      dockerStrategy: {}
      type: Docker
    successfulBuildsHistoryLimit: 5
parameters:
- name: REPO_NAME
  description: Application repository name
  required: true
- name: JOB_NAME
  description: Job identifier (i.e. 'pr-6' OR 'master')
  required: true
- name: SOURCE_REPO_REF
  description: Git Pull Request Reference (i.e. 'pull/CHANGE_ID/head')
  required: true
- name: SOURCE_REPO_URL
  description: Git Repository URL
  required: true
- name: APP_NAME
  description: Application name
  required: true
- name: NAMESPACE
  description: Target namespace reference (i.e. 'k8vopl-dev')
  required: true
