---
apiVersion: v1
kind: Template
labels:
  app: "${APP_NAME}-${JOB_NAME}"
  template: "${APP_NAME}-${JOB_NAME}-frontend-dc-template"
metadata:
  name: "${APP_NAME}-${JOB_NAME}-frontend-dc"
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: "${APP_NAME}-${JOB_NAME}-frontend"
  spec:
    ports:
    - name: 2015-tcp
      port: 2015
      protocol: TCP
      targetPort: 2015
    selector:
      app: "${APP_NAME}-${JOB_NAME}"
      deploymentconfig: "${APP_NAME}-${JOB_NAME}-frontend"
      role: frontend
    sessionAffinity: None
    type: ClusterIP
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: "${APP_NAME}-${JOB_NAME}-frontend"
  spec:
    replicas: 1
    selector:
      app: "${APP_NAME}-${JOB_NAME}"
      deploymentconfig: "${APP_NAME}-${JOB_NAME}-frontend"
      role: frontend
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: "${APP_NAME}-${JOB_NAME}"
          deploymentconfig: "${APP_NAME}-${JOB_NAME}-frontend"
          role: frontend
      spec:
        containers:
        - env:
          - name: PATH_ROOT
            value: "${PATH_ROOT}"
          - name: UI_SERVICE_PORT
            value: "2015"
          - name: STATIC_FILES_PATH
            value: "${STATIC_FILES_PATH}"
          - name: REACT_APP_API_ROOT
            value: "${PATH_ROOT}"
          - name: REACT_APP_CHES_ROOT
            value: "${PATH_ROOT}"
          - name: REACT_APP_CHES_PERFORMANCE_URL
            value: "${CHES_PERFORMANCE_URL}"
          - name: REACT_APP_UI_ROOT
            value: "${PATH_ROOT}"
          - name: REACT_APP_PUBLIC_URL
            value: "${HOST_URL}"
          - name: REACT_APP_OIDC_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: username
                name: "${OIDC_SECRET_NAME}"
          - name: REACT_APP_OIDC_ISSUER
            valueFrom:
              configMapKeyRef:
                key: OIDC_ISSUER
                name: "${OIDC_CONFIG_MAP_NAME}"
          image: "docker-registry.default.svc:5000/${NAMESPACE}/${REPO_NAME}-frontend:${JOB_NAME}"
          imagePullPolicy: Always
          # livenessProbe:
          #  failureThreshold: 3
          #  httpGet:
          #    path: "${PATH_ROOT}"
          #    port: 2015
          #    scheme: HTTP
          #  periodSeconds: 10
          #  successThreshold: 1
          #  timeoutSeconds: 1
          name: "${APP_NAME}-${JOB_NAME}-frontend"
          ports:
          - containerPort: 2015
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: "${PATH_ROOT}"
              port: 2015
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            requests:
              cpu: "${CPU_REQUEST}"
              memory: "${MEMORY_REQUEST}"
            limits:
              cpu: "${CPU_LIMIT}"
              memory: "${MEMORY_LIMIT}"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
parameters:
- name: REPO_NAME
  description: Application repository name
  required: true
- name: JOB_NAME
  description: Job identifier (i.e. 'pr-5' OR 'master')
  required: true
- name: NAMESPACE
  description: Target namespace reference (i.e. 'k8vopl-dev')
  required: true
- name: APP_NAME
  description: Application name
  required: true
- name: CPU_REQUEST
  description: Requested CPU per pod (in millicores ex. 500m)
  required: true
  value: 100m
- name: MEMORY_REQUEST
  description: Requested Memory per pod (in gigabytes Gi or megabytes Mi ex. 500Mi)
  required: true
  value: 256Mi
- name: CPU_LIMIT
  description: Limit Peak CPU per pod (in millicores ex. 1000m)
  required: true
  value: 500m
- name: MEMORY_LIMIT
  description: Limit Peak Memory per pod (in gigabytes Gi or megabytes Mi ex. 2Gi)
  required: true
  value: 1Gi
- name: PATH_ROOT
  description: Root of path where application is hosted (ex. '/pr-5' or '/mssc')
  required: true
  value: "/mssc"
- name: CHES_PERFORMANCE_URL
  description: the location for the CHES performance dashboard
  required: true
  value: https://metabase-9f0fbe-prod.pathfinder.gov.bc.ca/public/dashboard/6f388f95-dba7-4632-be4c-8855ee645f31
- name: STATIC_FILES_PATH
  description: where files are physically located on frontend caddy server
  required: true
  value: "/var/www/html"
- name: HOST_URL
  description: The full url for the application - the exposed route
  required: true
- name: OIDC_SECRET_NAME
  description: name of the User Auth / OIDC secret to pass in as environment variables
  required: true
  value: email-microsrv-oidc-client
- name: OIDC_CONFIG_MAP_NAME
  description: name of the User Auth / OIDC config map to pass in as environment variables
  required: true
  value: email-microsrv-oidc
