---
apiVersion: v1
kind: Template
labels:
  template: "${APP_NAME}-${JOB_NAME}-frontend-npm-bc-template"
metadata:
  name: "${APP_NAME}-${JOB_NAME}-frontend-npm-bc"
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: "${APP_NAME}-${JOB_NAME}"
    name: "${REPO_NAME}-frontend-npm"
  spec:
    lookupPolicy:
      local: false
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: "${APP_NAME}-${JOB_NAME}"
    name: "${APP_NAME}-${JOB_NAME}-frontend-npm"
  spec:
    completionDeadlineSeconds: 600
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: "${REPO_NAME}-frontend-npm:latest"
    postCommit: {}
    resources:
      requests:
        cpu: 1000m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 1Gi
    runPolicy: Serial
    source:
      contextDir: /frontend
      git:
        ref: "${SOURCE_REPO_REF}"
        uri: "${SOURCE_REPO_URL}"
      type: Git
      dockerfile: |-
        FROM mhart/alpine-node:12
        ARG APP_ROOT=/opt/app-root/src
        ARG XLSX_ROOT=${APP_ROOT}/node_modules/xlsx
        WORKDIR ${APP_ROOT}
        COPY package*.json ./
        RUN npm ci
        # serious monkey patching...
        # the package.json has a postinstall script to do this, but is not successful: npm WARN lifecycle
        # so we will manually copy this file over here
        # remove stuff we do not need, add the file we want...
        RUN rm -rf ${XLSX_ROOT}/bin && \
          rm ${XLSX_ROOT}/dist/*.min.js && \
          rm ${XLSX_ROOT}/dist/*.min.map && \
          rm ${XLSX_ROOT}/dist/*.extendscript.js && \
          rm ${XLSX_ROOT}/dist/xlsx.js && \
          rm ${XLSX_ROOT}/xlsx.mini.js
        COPY xlsx-override.js ${XLSX_ROOT}/xlsx.js
    strategy:
      dockerStrategy: {}
      type: Docker
    successfulBuildsHistoryLimit: 5
parameters:
- name: REPO_NAME
  description: Application repository name
  required: true
- name: JOB_NAME
  description: Job identifier (i.e. 'pr-5' OR 'master')
  required: true
- name: SOURCE_REPO_REF
  description: Git Pull Request Reference (i.e. 'pull/CHANGE_ID/head')
  required: true
- name: SOURCE_REPO_URL
  description: Git Repository URL
  required: true
- name: APP_NAME
  description: Application name
  required: true
