---
apiVersion: v1
kind: Template
labels:
  template: "${APP_NAME}-${JOB_NAME}-reverse-proxy-bc-template"
metadata:
  name: "${APP_NAME}-${JOB_NAME}-reverse-proxy-bc"
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: "${APP_NAME}-${JOB_NAME}"
    name: "${APP_NAME}-${JOB_NAME}-reverse-proxy"
  spec:
    lookupPolicy:
      local: false
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: "${APP_NAME}-${JOB_NAME}"
    name: "${APP_NAME}-${JOB_NAME}-reverse-proxy"
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: "${APP_NAME}-${JOB_NAME}-reverse-proxy:latest"
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: /reverse-proxy
      git:
        ref: "${SOURCE_REPO_REF}"
        uri: "${SOURCE_REPO_URL}"
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: s2i-caddy:v1-stable
          namespace: bcgov
      type: Source
    successfulBuildsHistoryLimit: 5
parameters:
- name: REPO_NAME
  description: Application repository name
  required: true
- name: JOB_NAME
  description: Job identifier (i.e. 'pr-5' OR 'master')
  required: true
- name: SOURCE_REPO_REF
  description: Git Pull Request Reference (i.e. 'pull/CHANGE_ID/head')
  required: true
- name: SOURCE_REPO_URL
  description: Git Repository URL
  required: true
- name: APP_NAME
  description: Application name
  required: true
