---
apiVersion: v1
kind: Template
labels:
  template: "${REPO_NAME}-${JOB_NAME}-reverse-proxy-bc-template"
metadata:
  name: "${REPO_NAME}-${JOB_NAME}-reverse-proxy-dc"
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: "${APP_NAME}-${JOB_NAME}"
    name: "${APP_NAME}-${JOB_NAME}-reverse-proxy"
  spec:
    ports:
    - name: 2015-tcp
      port: 2015
      protocol: TCP
      targetPort: 2015
    selector:
      app: "${APP_NAME}-${JOB_NAME}"
      deploymentconfig: "${APP_NAME}-${JOB_NAME}-reverse-proxy"
    sessionAffinity: None
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: "${APP_NAME}-${JOB_NAME}"
    name: "${APP_NAME}-${JOB_NAME}-reverse-proxy"
  spec:
    host: "${HOST_ROUTE}"
    path: "${PATH_ROOT}"
    port:
      targetPort: 2015-tcp
    to:
      kind: Service
      name: "${APP_NAME}-${JOB_NAME}-reverse-proxy"
      weight: 100
    wildcardPolicy: None
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: "${APP_NAME}-${JOB_NAME}"
    name: "${APP_NAME}-${JOB_NAME}-reverse-proxy"
  spec:
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      app: "${APP_NAME}-${JOB_NAME}"
      deploymentconfig: "${APP_NAME}-${JOB_NAME}-reverse-proxy"
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: "${APP_NAME}-${JOB_NAME}"
          deploymentconfig: "${APP_NAME}-${JOB_NAME}-reverse-proxy"
      spec:
        containers:
        - env:
          - name: PATH_ROOT
            value: "${PATH_ROOT}"
          - name: API_SERVICE_NAME
            value: "${API_SERVICE_NAME}"
          - name: API_SERVICE_PORT
            value: "${API_SERVICE_PORT}"
          - name: UI_SERVICE_NAME
            value: "${UI_SERVICE_NAME}"
          - name: UI_SERVICE_PORT
            value: "${UI_SERVICE_PORT}"
          image: "docker-registry.default.svc:5000/${NAMESPACE}/${APP_NAME}-${JOB_NAME}-reverse-proxy:latest"
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: "${PATH_ROOT}"
              port: 2015
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: "${APP_NAME}-${JOB_NAME}-reverse-proxy"
          ports:
          - containerPort: 2015
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - "${APP_NAME}-${JOB_NAME}-reverse-proxy"
        from:
          kind: ImageStreamTag
          name: "${APP_NAME}-${JOB_NAME}-reverse-proxy:latest"
      type: ImageChange
parameters:
- name: REPO_NAME
  description: Application repository name
  required: true
- name: JOB_NAME
  description: Job identifier (i.e. 'pr-5' OR 'master')
  required: true
- name: NAMESPACE
  description: Target namespace reference (i.e. 'k8vopl-dev')
  required: true
- name: APP_NAME
  description: Application name
  required: true
- name: HOST_ROUTE
  description: The host the route will use to expose service outside cluster
  required: true
- name: PATH_ROOT
  description: Root of path where application is hosted (ex. '/pr-5' or '/mssc')
  required: true
  value: "/mssc"
- name: API_SERVICE_NAME
  description: name of the api/backend service
  required: true
  value: "${APP_NAME}-${JOB_NAME}-backend"
- name: API_SERVICE_PORT
  description: port of the api/backend service
  required: true
  value: "8080"
- name: UI_SERVICE_NAME
  description: name of the ui/frontend service
  required: true
  value: "${APP_NAME}-${JOB_NAME}-frontend"
- name: UI_SERVICE_PORT
  description: port of the api/frontend service
  required: true
  value: "2015"
